### ISSUE TITLE
Unhandled rejection error

### ISSUE THREAD

**Issue by suissemaxx** [felixrieseberg/project-oxford#27]
While trying out your examples:

```
var oxford = require('project-oxford'),
    client = new oxford.Client('myAPIKey');

client.emotion.analyzeEmotion({
    path: "01.jpg",
}).then(function (response) {
    console.log(response);
});

```

 i get this error:

```
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/Users/Javascript/mstest/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/Users/Javascript/mstest/node_modules/bluebird/js/main/promise.js:472:22)
    at /Users/Javascript/mstest/node_modules/bluebird/js/main/promise.js:489:17
    at _return (/Users/Javascript/mstest/node_modules/project-oxford/dist/emotion.js:25:13)
    at Request._callback (/Users/Javascript/mstest/node_modules/project-oxford/dist/emotion.js:51:17)
    at Request.self.callback (/Users/Javascript/mstest/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Javascript/mstest/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Javascript/mstest/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

Maybe something very trivial i am missing. Any help is very much appreciated.

Thanks in advance.

**Comment by cthrash** [comment]
Can you tack on a error handler, like this?

```
client.emotion.analyzeEmotion({
    path: "01.jpg",
}).then(function (response) {
    console.log(response);
}).catch(function (err) {
    console.log(err);
});
```
The error message should help you narrow down the issue.

**Comment by cthrash** [comment]
Continuing on [SO](http://stackoverflow.com/questions/40078541/how-to-get-correct-subscription-key-for-microsoft-face-api-for-nodejs)
