### ISSUE TITLE
Unhandled rejection Error - client.emotion.analyzeEmotion

### ISSUE THREAD

**Issue by kdupreez** [felixrieseberg/project-oxford#31]
Tried to use the  client.emotion.analyzeEmotion sample and got this error.

Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/Code/node/cognitive/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/Code/node/cognitive/node_modules/bluebird/js/main/promise.js:472:22)
    at /Code/node/cognitive/node_modules/bluebird/js/main/promise.js:489:17
    at _return (/Code/node/cognitive/node_modules/project-oxford/dist/emotion.js:25:13)
    at Request._callback (/Code/node/cognitive/node_modules/project-oxford/dist/emotion.js:51:17)
    at Request.self.callback (/Code/node/cognitive/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Code/node/cognitive/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Code/node/cognitive/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

**Comment by cthrash** [comment]
You should add a error handler for the promise.  For example:

```
var oxford = require('project-oxford');
var client = new oxford.Client('wrong-key').emotion;

client.analyzeEmotion({url:'...'})
.catch(function(error) {
  console.log(JSON.stringify(error));
});
```
You would see something like: `{"error":{"code":"Unauthorized","message":"Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key."}}`

**Comment by kdupreez** [comment]
Ah.. Yeah, I used the face detection key..  

thanks!!!  (Weirdly, the face detection code already does this and throws wrong key error)
