### ISSUE TITLE
Unhandled rejection Error: [object Object]

### ISSUE THREAD

**Issue by fabnoe** [felixrieseberg/project-oxford#9]
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/Users/fnoethe/Documents/Dev/node_modules/project-oxford/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/Users/fnoethe/Documents/Dev/node_modules/project-oxford/node_modules/bluebird/js/main/promise.js:469:22)
    at /Users/fnoethe/Documents/Dev/node_modules/project-oxford/node_modules/bluebird/js/main/promise.js:486:17
    at _return (/Users/fnoethe/Documents/Dev/node_modules/project-oxford/dist/face.js:29:13)
    at Request._callback (/Users/fnoethe/Documents/Dev/node_modules/project-oxford/dist/face.js:88:24)
    at Request.self.callback (/Users/fnoethe/Documents/Dev/node_modules/project-oxford/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/fnoethe/Documents/Dev/node_modules/project-oxford/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/fnoethe/Documents/Dev/node_modules/project-oxford/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by fabnoe** [comment]
I used the emotion api key instead of the face api key. Everything is working now ;-)

**Comment by felixrieseberg** [comment]
I should probably document that though ;-)

**Comment by yysg** [comment]
Hello,i meet the same problem,but it does't work well when i chang the api key...,what should i do?

**Comment by cthrash** [comment]
What happens if you modify `face._return` to pass `JSON.stringify(response.body.error || response.body)` as an argument to `reject()`?  This should give you a better idea what the error is, instead of "[object Object]"

**Comment by yysg** [comment]
thanks ,it works!

**Comment by nikshepsvn** [comment]
@yysg any clue to how you fixed it?

**Comment by natcohen** [comment]
@felixrieseberg I'm also having this issue when I try to create a user... I'm using the credentials I use to login in cloudant. Is that correct?
